### PR TITLE
Log and return 403, in case AAD returns anything other than oAuth2 code

### LINKED ISSUE #184: If AAD fails to send oAuth2 code in the redirect after authentication, then return forbidden response
BP requests oAuth2 code while redirecting the user to AAD (OAuth2 server). But, in the redirect after authentication, AAD may send `error` instead of a oAuth2 code. 

Currently, BP redirects the user back to login page. But, that may put it in an infinite loop. Instead BP should log the error and return FORBIDDEN back to the user

### PR DESCRIPTION
**Pull request by maheshkelkar**
- also allow "space" in the query param

Fixes #184

### CODE REVIEW

File: auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala [hunk 1]
```diff
@@ -59,12 +57,18 @@ object LoginManagers {
     def codeToToken(req: BorderRequest): Future[Response] = {
       val hostStr = req.req.host.getOrElse(throw BpInvalidRequest(s"Host not found in HTTP $req"))
```
Comment (rikesh-chouhan) [inline auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala]: Isn't this an HTTP or HTTPS request, might confuse user to think somehow there is some unsecured connection. You can just remove HTTP from that message.

Comment (maheshkelkar) [inline auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala]: ok, done

File: auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala [hunk 2]
```diff
@@ -59,12 +57,18 @@ object LoginManagers {
...
       val scheme = req.req.headerMap.getOrElse("X-Forwarded-Proto", "http")
```
Comment (rikesh-chouhan) [inline auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala]: is this correct? Should it be https?

Comment (maheshkelkar) [inline auth/src/main/scala/com/lookout/borderpatrol/auth/tokenmaster/LoginManagers.scala]: No. "http" is default. Otherwise we take a value from "X-Forwarded-Proto"

**Comment by rikesh-chouhan** [comment]
+2
